# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2848b5d94713182e29c85bcd7f89000d43c12fc58a94150c59e425d2d2f2767abcf9375eabda6d9033ce68ccaae664df9b124380500e480a91065e56e8c50ea1

test:
  secret_key_base: 44fac63759f7658212adbdf3962e2152a07fd0911c0eeb941ee03c22937172127b31e7eeda0ee27a4184734b81d10bc61184a21d22e45aaa48480d306a1708bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
